# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-24 03:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Type',
            field=models.CharField(choices=[('Webuser', 'webuser'), ('Wwwroot', 'wwwroot')], default=datetime.datetime(2016, 9, 24, 3, 17, 57, 448163, tzinfo=utc), max_length=64, verbose_name='\u9879\u76ee\u7c7b\u578b'),
            preserve_default=False,
        ),
    ]
