# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-24 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AddField(
            model_name='project',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
