# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-24 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_auto_20160924_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='project',
            field=models.ManyToManyField(blank=True, to='deploy.Project'),
        ),
    ]
