# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-24 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_host_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deploy_dir',
            field=models.CharField(max_length=64, unique=True, verbose_name='\u90e8\u7f72\u76ee\u5f55'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
    ]
