# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-01 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0006_auto_20161001_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Type',
            field=models.CharField(choices=[('webuser', 'webuser'), ('wwwroot', 'wwwroot')], max_length=64, verbose_name='\u9879\u76ee\u7c7b\u578b'),
        ),
    ]
